environment:
    op_build_user: "OpenPublishBuild"
    op_build_user_email: "victor@victorprocure.co"
    access_token:
        secure: 2d7794f49ac54c21eed1fbfafbc9f23ed9c38bcc4006fb16b358985c7e279396

image: Visual Studio 2019
before_build:
    - ps: |
          if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
          {
              git checkout $env:APPVEYOR_REPO_BRANCH
              choco install docfx -y
          }

build_script:
    - msbuild SafeFileSystemWatcher.sln

after_build:
    - ps: |
          if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
          {
              & docfx docfx.json
              if($lastexitcode -ne 0){
                  throw [System.Exception] "DocFX build failed $lastexitcode"
              }

              git config --global credential.helper store
              Add-Content "$env:USERPROFILE\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
              git config --global user.email $env:op_build_user_email
              git config --global user.name $env:op_build_user

              git clone https://github.com/victorprocure/SafeFileSystemWatcher.git -b gh-pages origin_site -q
              Copy-Item origin_site/.git _site -recurse
              CD _site
              git add -A 2>&1
              git commit -m "CI Updates" -q
              git push origin gh-pages -q
          }