environment:
    op_build_user: "Victor Procure"
    op_build_user_email: "victor@victorprocure.co"
    access_token:
        secure: TBFC+GLl24sVXsrHdpL9YAR+3nRAnLHgH1ku+SbWnGQPbbLTm4fMEkgWQDqG6hSB

image: Visual Studio 2019
init:
    - cmd: git config --global core.autocrlf true

before_build:
    - ps: |
          if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
          {
              git checkout $env:APPVEYOR_REPO_BRANCH -q
              choco install docfx -y
              dotnet --version
              dotnet restore SafeFileSystemWatcher.sln --verbosity m
          }

build_script:
    - msbuild SafeFileSystemWatcher.sln

after_build:
    - ps: |
          if(-Not $env:APPVEYOR_PULL_REQUEST_TITLE)
          {
              & docfx docfx.json
              if($lastexitcode -ne 0){
                  throw [System.Exception] "DocFX build failed $lastexitcode"
              }

              git config --global credential.helper store
              Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
              git config --global user.email $env:op_build_user_email
              git config --global user.name $env:op_build_user

              git clone https://github.com/victorprocure/SafeFileSystemWatcher.git -b gh-pages origin_site -q
              Copy-Item origin_site/.git _site -recurse
              CD _site
              git add -A 2>&1
              git commit -m "CI Updates" -q
              git push origin gh-pages -q
          }

test_script:
  - cmd: dotnet test